// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAALldIDQNoS4y_agJo086MHWiTlIPFq18',
    appId: '1:389208310689:web:3646234565bd4696b041e0',
    messagingSenderId: '389208310689',
    projectId: 'life-savior-1f9b0',
    authDomain: 'life-savior-1f9b0.firebaseapp.com',
    storageBucket: 'life-savior-1f9b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKmFrNT4O6DBI-TgF2-NNPD665Eq7nlU0',
    appId: '1:389208310689:android:5bd06d8e1c9f2c45b041e0',
    messagingSenderId: '389208310689',
    projectId: 'life-savior-1f9b0',
    storageBucket: 'life-savior-1f9b0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpZk_gn-siUfVP9nnPLvgwkY81sPT0YQ',
    appId: '1:389208310689:ios:98bbfcba3a76db76b041e0',
    messagingSenderId: '389208310689',
    projectId: 'life-savior-1f9b0',
    storageBucket: 'life-savior-1f9b0.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpZk_gn-siUfVP9nnPLvgwkY81sPT0YQ',
    appId: '1:389208310689:ios:98bbfcba3a76db76b041e0',
    messagingSenderId: '389208310689',
    projectId: 'life-savior-1f9b0',
    storageBucket: 'life-savior-1f9b0.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAALldIDQNoS4y_agJo086MHWiTlIPFq18',
    appId: '1:389208310689:web:368fc0a9c60ad5a9b041e0',
    messagingSenderId: '389208310689',
    projectId: 'life-savior-1f9b0',
    authDomain: 'life-savior-1f9b0.firebaseapp.com',
    storageBucket: 'life-savior-1f9b0.firebasestorage.app',
  );
}
